name: corelate
description: Do more of what works.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+46

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.4
  riverpod_annotation: ^2.0.4
  riverpod_lint: ^1.2.0
  go_router: ^6.5.6
  copy_with_extension: ^5.0.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  appwrite: ^9.0.0
  wakelock: ^0.6.2
  intl: ^0.17.0
  health: ^5.0.0
  mindful_minutes: ^1.1.0
  flutter_native_splash: ^2.2.19
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  vibration: ^1.7.6
  fl_chart: ^0.61.0
  audioplayers: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  riverpod_generator: ^2.1.6
  copy_with_extension_gen: ^5.0.2
  isar_generator: ^3.0.5
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "F19D38"
  image: assets/icons/splash_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
